name: Run

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: [2000 2050,2050 2100,2100 2150,2150 2200,2200 2250,2250 2300,2300 2350,2350 2400,2400 2450,2450 2500,2500 2550,2550 2600,2600 2650,2650 2700,2700 2750,2750 2800,2800 2850,2850 2900,2900 2950,2950 3000]


    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install selenium
          python -m pip install names
          python -m pip install supabase
          sudo apt install -y google-chrome-stable
          sudo apt install -y xvfb
          export DISPLAY=:0
          /usr/bin/Xvfb :0 -screen 0 1024x768x24 &
          sleep 5
          xvfb-run python multi.py ${{matrix.RangeIndex}}
      - name: done
        run: exit
