name: Run

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: [7000 7050,7050 7100,7100 7150,7150 7200,7200 7250,7250 7300,7300 7350,7350 7400,7400 7450,7450 7500,7500 7550,7550 7600,7600 7650,7650 7700,7700 7750,7750 7800,7800 7850,7850 7900,7900 7950,7950 8000]


    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install selenium
          python -m pip install names
          python -m pip install supabase
          sudo apt install -y google-chrome-stable
          sudo apt install -y xvfb
          export DISPLAY=:0
          /usr/bin/Xvfb :0 -screen 0 1024x768x24 &
          sleep 5
          xvfb-run python multi.py ${{matrix.RangeIndex}}
      - name: done
        run: exit
